server {
    listen 80;
    server_name worshipmusicacademy.localhost localhost;

    client_max_body_size 128M;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ^~ /app/index.php {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/codeigniter/public/index.php;
        fastcgi_param SCRIPT_NAME /app/index.php;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param DOCUMENT_ROOT /var/www/codeigniter/public;
    }

    location ^~ /app/ {
        alias /var/www/codeigniter/public/;
        index index.php index.html;
        try_files $uri $uri/ @app;
    }

    location @app {
        rewrite ^/app/(.*)$ /app/index.php/$1 last;
    }

    location ~ ^/app/(.+\.php)$ {
        return 404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
    }

    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|svg|webp|woff|woff2|ttf|eot)$ {
        expires 7d;
        access_log off;
        try_files $uri $uri/ /index.php?$args;
    }
}
